# Numpy Array Operations

In [2]:
import numpy as np

In [3]:
# Indexing and slicing in NumPy arrays is similar to Python lists but with some additional features. Here are some examples:

arr = np.arange(1,10) # Create a 1D array from 1 to 9
print("Original array:", arr)
print("Element at index 2:", arr[2])  # Accessing the 3rd element (index starts at 0)
print("Basic slicing (2:5):", arr[2:5])  # Slicing from index 2 to 4
print("Slicing with step (0:9:2):", arr[0:9:2])  # Slicing with a step of 2
print("Negative indexing (last element):", arr[-1])  # Accessing the last element
print("Negative slicing (-5:-2):", arr[-5:-2])  # Slicing using negative indices

Original array: [1 2 3 4 5 6 7 8 9]
Element at index 2: 3
Basic slicing (2:5): [3 4 5]
Slicing with step (0:9:2): [1 3 5 7 9]
Negative indexing (last element): 9
Negative slicing (-5:-2): [5 6 7]


In [4]:
arr_2d = np.arange(1,10).reshape(3,3) # Create a 2D array (3x3)
print("\n2D Array:\n", arr_2d)
print("Specific element (row 1, column 2):", arr_2d[1, 2])  # Accessing element at row 1, column 2
print("Entire row (row 1):", arr_2d[1, :])  # Accessing the entire first row
print("Entire column (column 1):", arr_2d[:, 1])  # Accessing the entire third column
print("Slicing a subarray (rows 0-1, columns 0-1):\n", arr_2d[0:2, 0:2])  # Slicing a subarray


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element (row 1, column 2): 6
Entire row (row 1): [4 5 6]
Entire column (column 1): [2 5 8]
Slicing a subarray (rows 0-1, columns 0-1):
 [[1 2]
 [4 5]]


# Sorting

In [7]:
unsorted_arr = np.array([5, 2, 9, 1, 5, 6])
sorted_arr = np.sort(unsorted_arr)
print("\nUnsorted array:", unsorted_arr)
print("Sorted array:", sorted_arr)

unsorted_arr_2d = np.array([[3, 1, 2], [9, 5, 6], [8, 7, 4]])
sorted_arr_2d = np.sort(unsorted_arr_2d, axis=0)  # Sort along columns (top to bottom data is sorted)
print("\nUnsorted 2D array:\n", unsorted_arr_2d)
print("Sorted 2D array (by columns):\n", sorted_arr_2d)
sorted_arr_2d_row = np.sort(unsorted_arr_2d, axis=1)  # Sort along rows (left to right data is sorted)
print("Sorted 2D array (by rows):\n", sorted_arr_2d_row)


Unsorted array: [5 2 9 1 5 6]
Sorted array: [1 2 5 5 6 9]

Unsorted 2D array:
 [[3 1 2]
 [9 5 6]
 [8 7 4]]
Sorted 2D array (by columns):
 [[3 1 2]
 [8 5 4]
 [9 7 6]]
Sorted 2D array (by rows):
 [[1 2 3]
 [5 6 9]
 [4 7 8]]


# Filtering & Filter with Mask

In [20]:
arr = np.arange(1,10)
print("\nOriginal array:", arr)
even_arr = arr[arr % 2 == 0]  # Filter even numbers
print("Even numbers:", even_arr)

mask = (arr % 2 == 0)  # Create a boolean mask for even numbers, basically it just stores the expression written above in this variable
print("Boolean mask for even numbers:", mask)
print("Filtered array using boolean mask:", arr[mask]) # Apply the boolean mask to filter the array, it will return only those elements where the mask is True, which are the even numbers in this case.

mask = (arr > 5) & (arr < 8)  # Create a boolean mask for numbers greater than 5 and less than 8
print("Boolean mask for numbers > 5 and < 8:", mask)
print("Filtered array using boolean mask:", arr[mask])  # Apply the boolean mask to filter the array, it will return only those elements where the mask is True, which are the numbers greater than 5 and less than 8 in this case.

# For 2D arrays, you can use boolean indexing to filter rows or columns based on conditions. For example, to filter rows where the first column is greater than 5:
arr_2d = np.array([[1, 2], [6, 7], [3, 4], [8, 9]])
print("\nOriginal 2D array:\n", arr_2d)
mask = arr_2d[:, 0] > 5  # Create a boolean mask for rows where the first column is greater than 5  
print("Boolean mask for rows where the first column is greater than 5:", mask)
print("Filtered 2D array using boolean mask:\n", arr_2d[mask, :])  # Apply the boolean mask to filter the rows, it will return only those rows where the first column is greater than 5 in this case.

# Filtering columns based on conditions can be done similarly. For example, to filter columns where the first row is less than 5:
mask = arr_2d[0, :] < 5  # Create a boolean mask
print("Boolean mask for columns where the first row is less than 5:", mask)
print("Filtered 2D array using boolean mask:\n", arr_2d[:, mask])  # Apply the boolean mask to filter columns (axis 1), returning only columns where the first row is < 5.


Original array: [1 2 3 4 5 6 7 8 9]
Even numbers: [2 4 6 8]
Boolean mask for even numbers: [False  True False  True False  True False  True False]
Filtered array using boolean mask: [2 4 6 8]
Boolean mask for numbers > 5 and < 8: [False False False False False  True  True False False]
Filtered array using boolean mask: [6 7]

Original 2D array:
 [[1 2]
 [6 7]
 [3 4]
 [8 9]]
Boolean mask for rows where the first column is greater than 5: [False  True False  True]
Filtered 2D array using boolean mask:
 [[6 7]
 [8 9]]
Boolean mask for columns where the first row is less than 5: [ True  True]
Filtered 2D array using boolean mask:
 [[1 2]
 [6 7]
 [3 4]
 [8 9]]


In [23]:
# Filter both rows and columns based on conditions. For example, to filter rows where the first column is greater than 5 and columns where the first row is less than 5:
row_mask = arr_2d[:, 0] > 5  # Mask for rows
col_mask = arr_2d[0, :] < 5  # Mask for columns
print("Row mask for rows where the first column is greater than 5:", row_mask)
print("Column mask for columns where the first row is less than 5:", col_mask)
print("Filtered 2D array using both row and column masks:\n", arr_2d[row_mask, :][:, col_mask])  # Apply both masks to filter rows and columns, returning only the elements that satisfy both conditions.

Row mask for rows where the first column is greater than 5: [False  True False  True]
Column mask for columns where the first row is less than 5: [ True  True]
Filtered 2D array using both row and column masks:
 [[6 7]
 [8 9]]


# Fancy Indexing vs np.where()

In [28]:
indexes = np.array([0, 2, 4, 6])  # Indices of rows to keep
num = np.arange(1,10)
print("\nOriginal array:", num)
print("Selected elements at indexes:", indexes, ":", num[indexes])

where_mask = np.where(num % 2 == 0)  # Get indices of even numbers
print("Even numbers using np.where:", num[where_mask])  # Use the indices to filter the array, returning only the even numbers.

condition_array = np.where(num % 2 == 0, num, -1)  # Create a new array where even numbers are kept and odd numbers are replaced with -1
print("Array with even numbers and -1 for odd numbers:", condition_array)
# or like this
condition_array = np.where(num % 2 == 0, "true", "false")
print("Array with 'true' for even numbers and 'false' for odd numbers:", condition_array)
# or like this
condition_array = np.where(num % 2 == 0, "Even", "Odd")
print("Array with 'Even' for even numbers and 'Odd' for odd numbers:", condition_array)

# So where() doesnt just filter the array but it can also be used to create new arrays based on conditions, which is a powerful feature for data manipulation and analysis.


Original array: [1 2 3 4 5 6 7 8 9]
Selected elements at indexes: [0 2 4 6] : [1 3 5 7]
Even numbers using np.where: [2 4 6 8]
Array with even numbers and -1 for odd numbers: [-1  2 -1  4 -1  6 -1  8 -1]
Array with 'true' for even numbers and 'false' for odd numbers: ['false' 'true' 'false' 'true' 'false' 'true' 'false' 'true' 'false']
Array with 'Even' for even numbers and 'Odd' for odd numbers: ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd']


# Operations on Data

In [29]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
result = np.add(arr_1, arr_2)  # Element-wise addition
print("\nElement-wise addition of arr_1 and arr_2:", result)
result = np.multiply(arr_1, arr_2)  # Element-wise multiplication
print("Element-wise multiplication of arr_1 and arr_2:", result)
result = np.dot(arr_1, arr_2)  # Dot product
print("Dot product of arr_1 and arr_2:", result)
result = np.sum(arr_1)  # Sum of elements in arr_1
print("Sum of elements in arr_1:", result)
result = np.mean(arr_1)  # Mean of elements in arr_1
print("Mean of elements in arr_1:", result)
result = np.std(arr_1)  # Standard deviation of elements in arr_1
print("Standard deviation of elements in arr_1:", result)
result = np.min(arr_1)  # Minimum value in arr_1
print("Minimum value in arr_1:", result)
result = np.max(arr_1)  # Maximum value in arr_1
print("Maximum value in arr_1:", result)    
result = np.argmin(arr_1)  # Index of minimum value in arr_1
print("Index of minimum value in arr_1:", result)
result = np.argmax(arr_1)  # Index of maximum value in arr_1
print("Index of maximum value in arr_1:", result)
result = np.concatenate((arr_1, arr_2))  # Concatenate arr_1 and arr_2
print("Concatenation of arr_1 and arr_2:", result)
result = np.unique(np.array([1, 2, 2, 3, 3, 3]))  # Unique elements in the array
print("Unique elements in the array:", result) 
result = np.argsort(arr_1)  # Indices that would sort arr_1
print("Indices that would sort arr_1:", result)



Element-wise addition of arr_1 and arr_2: [5 7 9]
Element-wise multiplication of arr_1 and arr_2: [ 4 10 18]
Dot product of arr_1 and arr_2: 32
Sum of elements in arr_1: 6
Mean of elements in arr_1: 2.0
Standard deviation of elements in arr_1: 0.816496580927726
Minimum value in arr_1: 1
Maximum value in arr_1: 3
Index of minimum value in arr_1: 0
Index of maximum value in arr_1: 2
Concatenation of arr_1 and arr_2: [1 2 3 4 5 6]
Unique elements in the array: [1 2 3]
Indices that would sort arr_1: [0 1 2]


# Array Compatibility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])  # This will cause a broadcasting error due to different shapes
c = np.array([7, 8, 9])

print("Compatible shapes for broadcasting: ", a.shape == b.shape == c.shape)  # Output: False
print("Compatible shapes for broadcasting: ", a.shape == c.shape)  # Output: True

Compatible shapes for broadcasting:  False
Compatible shapes for broadcasting:  True


# Adding a new row

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
new_row = np.array([6, 7, 8, 9, 10])

result = np.vstack((original_array, new_row))  # Stack arrays vertically (row-wise)
print("\nOriginal array:", original_array)
print("New row to add:", new_row)
print("Result of vertical stacking:\n", result)

# Takes a tuple as input in both vstack and hstack, so we need to put the arrays inside a tuple, which is done by using double parentheses ((original_array, new_row)) instead of single parentheses (original_array, new_row). 
# This is necessary because the functions expect a single argument that is a tuple containing the arrays to be stacked.




Original array: [1 2 3 4 5]
New row to add: [ 6  7  8  9 10]
Result of vertical stacking:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Adding a new column

In [32]:
original_array = np.array([1, 2, 3, 4, 5])
new_column = np.array([6, 7, 8, 9, 10])

result = np.column_stack((original_array, new_column))  # Stack arrays horizontally (column-wise)
print("\nOriginal array:", original_array)
print("New column to add:", new_column)
print("Result of horizontal stacking:\n", result)



Original array: [1 2 3 4 5]
New column to add: [ 6  7  8  9 10]
Result of horizontal stacking:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# Deletion

In [34]:
original_array = np.array([1, 2, 3, 4, 5])
deleted = np.delete(original_array, 2)  # Delete the element at index 2 (the value 3)
print("\nOriginal array:", original_array)
print("Array after deleting element at index 2:", deleted)

# So in this example, the original array remains unchanged, and a new array is created with the specified element removed. 
# The np.delete() function is useful for removing elements from an array based on their index.
# And unlike other langs it doesnt give back the popped element instead it gives back the new array with the element removed, so if you want to get the popped element you can do it like this:
popped_element = original_array[2]  # Get the element at index 2 before deletion
deleted = np.delete(original_array, 2)  # Delete the element at index 2
print("Popped element:", popped_element)
print("Array after deletion:", deleted)


Original array: [1 2 3 4 5]
Array after deleting element at index 2: [1 2 4 5]
Popped element: 3
Array after deletion: [1 2 4 5]
