<!-- The core of NumPy is the array. While it looks like a Python list, it is stored differently in memory, making it much faster for mathematical calculations.
Under the hood it works on C++
We usually import numpy as np
[1,2,3,4,5] -> vector, 1D array
[[1,2,3],[4,5,6],[7,8,9]] -> matrices, 2D Array  -->

In [29]:
import numpy as np

In [30]:
# Creating a 1D Array (Vector)
vec = np.array([1, 2, 3, 4, 5])
print("1D Array (Vector):", vec)

# Creating a 2D Array (Matrix)
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("2D Array (Matrix):\n", mat)


1D Array (Vector): [1 2 3 4 5]
2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# NumPy has built-in functions to generate specific types of data such as:
# np.zeroes(): Creates an array filled with zeros.
# np.ones(): Creates an array filled with ones.
# np.full(): Creates an array filled with a specified value.
# np.eye(): Creates an identity matrix.
# np.arange(): Creates an array with a range of values.
# np.linspace(): Creates an array with evenly spaced values over a specified interval.

arr = np.zeros((3, 4))  # 3 rows, 4 columns
print("Array of zeros:\n", arr)
arr = np.ones((2, 5))  # 2 rows, 5 columns
print("Array of ones:\n", arr)
arr = np.full((3, 3), 7)  # 3x3 array filled with 7
print("Array filled with 7:\n", arr)
arr = np.eye(4)  # 4x4 identity matrix
print("Identity matrix:\n", arr)
arr = np.arange(0, 10, 2)  # Array of even numbers
print("Array of even numbers from 0 to 10:\n", arr)
arr = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
print("Array of evenly spaced values from 0 to 1:\n", arr)
arr = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1
print("Array of random values:\n", arr)

Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array of even numbers from 0 to 10:
 [0 2 4 6 8]
Array of evenly spaced values from 0 to 1:
 [0.   0.25 0.5  0.75 1.  ]
Array of random values:
 [[0.51911396 0.46207032 0.15673236]
 [0.01897486 0.86928969 0.03362945]
 [0.34972225 0.6140676  0.14071489]]


In [32]:
# Creating a 3D Array (Tensor)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array (Tensor):\n", tensor)

tensor = np.zeros((2, 3, 4))  # 2 blocks, 3 rows, 4 columns
print("3D Array of zeros:\n", tensor)



3D Array (Tensor):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3D Array of zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [33]:
# In AI/ML, we often work with multi-dimensional arrays (tensors) to represent data such as images, videos, and sequences. For example:
# - A grayscale image can be represented as a 2D array (height x width).
# - A color image can be represented as a 3D array (height x width x channels).
# - A batch of images can be represented as a 4D array (batch size x height x width x channels).    
# Also we need to know how to interrogate an array
# we often get errors beacuse the shape of your data doesnt match what an algorithm expects.
'''
shape: A tuple representing the dimensions of the array. For example, a 2D array with 3 rows and 4 columns would have a shape of (3, 4).
size: The total number of elements in the array. This is the product of the dimensions. For example, a 2D array with a shape of (3, 4) would have a size of 12 (3 rows x 4 columns).
ndim: The number of dimensions in the array. For example, a 2D array would have ndim = 2, while a 3D array would have ndim = 3.
dtype: The data type of the elements in the array. For example, an array of integers would have dtype = int, while an array of floating-point numbers would have dtype = float.

Pro tip: ML Models often use float32 data type for better performance and save memeory.
'''


'\nshape: A tuple representing the dimensions of the array. For example, a 2D array with 3 rows and 4 columns would have a shape of (3, 4).\nsize: The total number of elements in the array. This is the product of the dimensions. For example, a 2D array with a shape of (3, 4) would have a size of 12 (3 rows x 4 columns).\nndim: The number of dimensions in the array. For example, a 2D array would have ndim = 2, while a 3D array would have ndim = 3.\ndtype: The data type of the elements in the array. For example, an array of integers would have dtype = int, while an array of floating-point numbers would have dtype = float.\n\nPro tip: ML Models often use float32 data type for better performance and save memeory.\n'

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape, arr.size, arr.ndim, arr.dtype)

# In Data Science and Machine Learning, understanding the shape, size, dimensions, and data type of your arrays is crucial for debugging and ensuring that your data is in the correct format for your models.
# You'll constantly need to change how data is organized without changing the data itself.

# Reshaping an array
reshaped_arr = arr.reshape(3, 2)  # Reshape to 3 rows and 2 columns
print("Original Array:\n", arr)
print("Reshaped Array:\n", reshaped_arr)

# Flattening an array (by value, creates a copy, nothing to do with the original array, original array is unchanged)
flattened_arr = arr.flatten()  # Flatten to a 1D array
print("Flattened Array:\n", flattened_arr)

# Raveling an array (by reference if possible)
raveled_arr = arr.ravel()  # Ravel to a 1D array (similar to flatten but returns a view if possible, instead of a copy)
print("Raveled Array:\n", raveled_arr)

# Transposing an array
new_arr = np.arange(1, 7).reshape(2, 3)  # Create a 2x3 array
print("Original Array:\n", new_arr)
transposed_arr = new_arr.T  # Transpose the array
print("Transposed Array:\n", transposed_arr)



(2, 3) 6 2 int64
Original Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened Array:
 [1 2 3 4 5 6]
Raveled Array:
 [1 2 3 4 5 6]
Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [37]:
# Python list multiplication creates a new list by repeating the original list a specified number of times. For example:
my_list = [1, 2, 3]
multiplied_list = my_list * 3
print(multiplied_list)  # Output: [1, 2, 3, 1, 2, 3, 1, 2, 3]

# In contrast, NumPy array multiplication performs element-wise multiplication when you multiply an array by a scalar. For example:
my_array = np.array([1, 2, 3])
multiplied_array = my_array * 3
print(multiplied_array)  # Output: [3, 6, 9]


[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
