# Vectorization
Vectorization in NumPy is the process of applying operations to entire arrays at once, rather than iterating through individual elements using explicit Python for loops

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
result = arr + 1
print(result)  # Output: [2 3 4]

# So this is how vectorization works in NumPy. Instead of writing a loop to add 1 to each element,
# we can simply perform the operation on the entire array, and NumPy will handle it efficiently under the hood.
result = arr * 2
print(result)  # Output: [2 4 6]
result = arr ** 2
print(result)  # Output: [1 4 9]
result = arr - 1
print(result)  # Output: [0 1 2]
result = arr / 2
print(result)  # Output: [0.5 1.  1.5]
result = arr % 2
print(result)  # Output: [1 0 1]
result = arr // 2
print(result)  # Output: [0 1 1]


[2 3 4]
[2 4 6]
[1 4 9]
[0 1 2]
[0.5 1.  1.5]
[1 0 1]
[0 1 1]


In [7]:
# np.where(condition, value_if_true, value_if_false)
scores = np.array([85, 92, 78, 99, 88])
capped_scores = np.where(scores > 90, 90, scores)
print(capped_scores)  # Output: [85 90 78 90 88]

[85 90 78 90 88]
